---
title: "GET08_TA"
output: word_document
---

# Load packages
```{r}
library(tm)
library(pdftools)
library(NMF)
library(svs)
library(lsa)
library(dplyr)
library(topicmodels)
library(tidyr)
library(tidytext)
```


### Data Preparation
```{r}
getwd()
setwd("C:/Users/xoxox/polybox/Master/3. Semester/Governing the Energy Transition/GET Seminar Paper/Bills/116th Congress/116_reduced_below300")
files <- list.files(pattern = "pdf$")
files # 45

billtext <- lapply(files, pdf_text)

length(billtext) 
x <- lapply(billtext, length) 

# Transform billnr_dt to dataframe
billnr_df <- as.data.frame(x)
colnames(billnr_df) <- files
billnr_df


# Rename bills
newname <- c("H.R.1009", "H.R.1136", "H.R.1315", "H.R.1742", "H.R.2096", "H.R.2170", "H.R.2741", "H.R.2764", "H.R.2831", "H.R.3423", "H.R.3597", "H.R.3973", "H.R.4061", "H.R.4520", "H.R.4649", "H.R.482",  "H.R.4863", "H.R.5091", "H.R.5164", "H.R.5185", "H.R.704",  "S.1085", "S.1142",   "S.1427",  "S.1487",   "S.1528",   "S.1740", "S.1741",   "S.1742",   "S.1750",  "S.2", "S.2040",   "S.2193",   "S.2277",  "S.2393", "S.2403",   "S.2447",   "S.2668",  "S.2876",   "S.2882", "S.2947",   "S.343",    "S.346",    "S.47",     "S.79")

names(billnr_df) <- newname


# Barplot with number of bills
# pdf("barplot_116_reverse2.pdf")
barplot(sort(as.matrix(billnr_df), decreasing = T), las = 2, cex.names = 0.6, ylim = c(0,300),names.arg = colnames(sort((billnr_df), decreasing = T)), xlab = "Legislation Numbers",ylab = "Number of Pages per Legisaltion")
# abline(h = , col = "gray60", lty = 2)
# dev.off()
```



```{r}

# CREATE A CORPUS
corp <- Corpus(URISource(files), # Uniform Resource Identifier
               readerControl = list(reader = readPDF))


# Clean Data
removedwords <- c("aa", "aaa", "bb", "bbb", "cc", "ccc", "dd", "ddd", "ee", "eee", "ff", "fff", "gg", "ggg", "hh", "hhh", "ii", "iii", "jj", "jjj", "kk", "kkk", "ll", "lll", "mm", "mmm", "nn", "nnn", "oo", "ooo", "pp", "ppp", "qq", "qqq", "rr", "rrr", "ss", "sss", "tt", "ttt", "uu", "uuu", "vv", "vvv", "ww", "www", "xx", "xxx", "yy", "yyy", "zz", "zzz", "iv", "vi", "vii", "viii", "ix", "ai", "aii", "aiii", "aiiii", "aiiiii", "§", "section", "sec.", "bill", "bills", "BILLS", "Bill", "frm", "Frm", "fmt", "Fmt", "sfmt", "Sfmt", "jkt", "Jkt", "act", "(", ")", "''§", "''''", "'a", ".HR", "HR", "DSKDCPROD", "DSK")

corp_clean <- tm_map(corp, removeWords, removedwords)

corp_clean <- tm_map(corp_clean, content_transformer(tolower))

corp_clean <- tm_map(corp_clean, removeNumbers)
corp_clean <- tm_map(corp_clean, removeWords, stopwords())
corp_clean <- tm_map(corp_clean, removePunctuation)
corp_clean <- tm_map(corp_clean, stripWhitespace)
corp_clean <- tm_map(corp_clean, stemDocument)



######## NORMAL ##########

# Prepare Term-Document Matrix
dtm <- DocumentTermMatrix(corp_clean)
inspect(dtm) # 92% sparsity

# Number of documents and terms
dim(dtm) # 45 documents, 8683 terms  

# Drop very rare terms
dtm <- removeSparseTerms(dtm, 0.97) 
dtm2$ncol # 3988 
inspect(dtm) # 86% sparsity

# Transpose: Term Dokument Matrix
tdm <- t(dtm)


######## TF-IDF ##########


# creating term matrix with TF-IDF weighting
dtm_tfidf <-DocumentTermMatrix(corp_clean,control = list(weighting = function(x) weightTfIdf(x, normalize = FALSE)))
dtm_tfidf$ncol # 8683
inspect(dtm_tfidf) # 93% sparsity

# Drop very rare terms
dtm_tfidf <- removeSparseTerms(terms, 0.97)
dtm_tfidf$ncol # 3972
inspect(dtm_tfidf) # 91%

# Transpose: Term Document Matrix
tdm_tfidf <- t(dtm_tfidf)

```



### NMF ###
###########

- non-negative matrix factorization
- Kullback-Leibler criterion to perform the factorization

```{r}

# retain 4 topics
#################
set.seed(40)

nnf.fit4 <- fast_nmf(as.matrix(dtm), 4, type = "KL", tol = 1e-16)

head(sort(round(nnf.fit4$pos2, 0)[1,], decreasing = T), n = 20) # land and water management
head(sort(round(nnf.fit4$pos2, 0)[2,], decreasing = T), n = 20) # energy prgram
head(sort(round(nnf.fit4$pos2, 0)[3,], decreasing = T), n = 20) # energy electricity technology program
head(sort(round(nnf.fit4$pos2, 0)[4,], decreasing = T), n = 15) # us-china


set.seed(40)

nnf.fit4 <- fast_nmf(as.matrix(dtm_tfidf), 4, type = "KL", tol = 1e-16)

head(sort(round(nnf.fit4$pos2, 0)[1,], decreasing = T), n = 20) 
head(sort(round(nnf.fit4$pos2, 0)[2,], decreasing = T), n = 20) 
head(sort(round(nnf.fit4$pos2, 0)[3,], decreasing = T), n = 20) 
head(sort(round(nnf.fit4$pos2, 0)[4,], decreasing = T), n = 15) 


# retain 5 topics
#################
set.seed(40)

nnf.fit5 <- fast_nmf(as.matrix(dtm), 5, type = "KL", tol = 1e-16)

head(sort(round(nnf.fit5$pos2, 0)[1,], decreasing = T), n = 20) 
head(sort(round(nnf.fit5$pos2, 0)[2,], decreasing = T), n = 20) 
head(sort(round(nnf.fit5$pos2, 0)[3,], decreasing = T), n = 15) 
head(sort(round(nnf.fit5$pos2, 0)[4,], decreasing = T), n = 15) 
head(sort(round(nnf.fit5$pos2, 0)[5,], decreasing = T), n = 30) 

set.seed(40)

nnf.fit5 <- fast_nmf(as.matrix(dtm_tfidf), 5, type = "KL", tol = 1e-16)

head(sort(round(nnf.fit5$pos2, 0)[1,], decreasing = T), n = 20) 
head(sort(round(nnf.fit5$pos2, 0)[2,], decreasing = T), n = 20) 
head(sort(round(nnf.fit5$pos2, 0)[3,], decreasing = T), n = 15) 
head(sort(round(nnf.fit5$pos2, 0)[4,], decreasing = T), n = 15) 
head(sort(round(nnf.fit5$pos2, 0)[5,], decreasing = T), n = 30) 

# retain 6 topics => BEST REPRESENTATION OF TOPICS
###################################################
set.seed(40)

nnf.fit6 <- fast_nmf(as.matrix(dtm), 6, type = "KL", tol = 1e-16)
head(sort(round(nnf.fit6$pos2, 0)[1,], decreasing = T), n = 20) 
head(sort(round(nnf.fit6$pos2, 0)[2,], decreasing = T), n = 20) 
head(sort(round(nnf.fit6$pos2, 0)[3,], decreasing = T), n = 20) 
head(sort(round(nnf.fit6$pos2, 0)[4,], decreasing = T), n = 20) 
head(sort(round(nnf.fit6$pos2, 0)[5,], decreasing = T), n = 15)  
head(sort(round(nnf.fit6$pos2, 0)[6,], decreasing = T), n = 25) 


set.seed(40)

nnf.fit6 <- fast_nmf(as.matrix(dtm_tfidf), 6, type = "KL", tol = 1e-16)
head(sort(round(nnf.fit6$pos2, 0)[1,], decreasing = T), n = 20) 
head(sort(round(nnf.fit6$pos2, 0)[2,], decreasing = T), n = 20) 
head(sort(round(nnf.fit6$pos2, 0)[3,], decreasing = T), n = 20) 
head(sort(round(nnf.fit6$pos2, 0)[4,], decreasing = T), n = 20) 
head(sort(round(nnf.fit6$pos2, 0)[5,], decreasing = T), n = 15) 
head(sort(round(nnf.fit6$pos2, 0)[6,], decreasing = T), n = 25) 

# retain 7 topics 
#################
set.seed(40) 

nnf.fit7 <- fast_nmf(as.matrix(dtm), 7, type = "KL", tol = 1e-16)

head(sort(round(nnf.fit7$pos2, 0)[1,], decreasing = T), n = 15) 
head(sort(round(nnf.fit7$pos2, 0)[2,], decreasing = T), n = 15) 
head(sort(round(nnf.fit7$pos2, 0)[3,], decreasing = T), n = 15)  
head(sort(round(nnf.fit7$pos2, 0)[4,], decreasing = T), n = 15) 
head(sort(round(nnf.fit7$pos2, 0)[5,], decreasing = T), n = 15) 
head(sort(round(nnf.fit7$pos2, 0)[6,], decreasing = T), n = 15) 
head(sort(round(nnf.fit7$pos2, 0)[7,], decreasing = T), n = 20) 


set.seed(40) 

nnf.fit7 <- fast_nmf(as.matrix(dtm_tfidf), 7, type = "KL", tol = 1e-16)

head(sort(round(nnf.fit7$pos2, 0)[1,], decreasing = T), n = 15) 
head(sort(round(nnf.fit7$pos2, 0)[2,], decreasing = T), n = 15) 
head(sort(round(nnf.fit7$pos2, 0)[3,], decreasing = T), n = 15)  
head(sort(round(nnf.fit7$pos2, 0)[4,], decreasing = T), n = 15) 
head(sort(round(nnf.fit7$pos2, 0)[5,], decreasing = T), n = 15) 
head(sort(round(nnf.fit7$pos2, 0)[6,], decreasing = T), n = 15) 
head(sort(round(nnf.fit7$pos2, 0)[7,], decreasing = T), n = 20) 


# NOTE: 
# - pay attention to seed, different seeds change the frequency of the words and thus the most frequenent words.
# - retaining 6 topics gives the best distinction of categries


# Which topic is represented most in which document?
# this is interesting for further analyses!!
# careful, nnm.fit for original data and for tfidf data have the same name -> specify before runing next line
round(nnf.fit6$pos1, round(4))

```



### PLSA ###
############

- given latent topic X, what are the conditional document probabilities?
- given latent topic X, which are the 15 largest condtitional term probabilities?



```{r}
# library(parallel)
# library(doParallel)
# K <- parallel::detectCores()
# cl <- makeCluster(K)
# registerDoParallel(cl)

set.seed(40)
plsa.fit6 <- fast_psa(as.matrix(dtm), 6, symmetric = T) ###

set.seed(40)
plsa.fit5 <- fast_psa(as.matrix(dtm), 5, symmetric = T) ###

#1. What probabilities are associated with the different topics?
plsa.fit6$prob0
plsa.fit5$prob0


## TOPIC 1 ##
sort(plsa.fit6$prob2[,1], decreasing = T)[1:15]  ## LAND AND WATER MANAGEMENT
sort(round(plsa.fit6$prob1[,1], 5), decreasing = T)

sort(plsa.fit5$prob2[,1], decreasing = T)[1:15]  ## LAND AND WATER MANAGEMENT
sort(round(plsa.fit5$prob1[,1], 5), decreasing = T)


## TOPIC 2 ##
sort(plsa.fit6$prob2[,2], decreasing = T)[1:15]  ## ENERGY PROGRAM
sort(round(plsa.fit6$prob1[,2], 5), decreasing = T) 

sort(plsa.fit5$prob2[,2], decreasing = T)[1:15]  ## ENERGY PROGRAM
sort(round(plsa.fit5$prob1[,2], 5), decreasing = T) 


## TOPIC 3 ##
sort(plsa.fit6$prob2[,3], decreasing = T)[1:15] ## ENERGY INDUSTRY DEVELOPMENT PROGRAM/GRANT
sort(round(plsa.fit6$prob1[,3], 5), decreasing = T) 
 
sort(plsa.fit5$prob2[,3], decreasing = T)[1:15] ## US-CHINA VEHICLE EMISSIONS
sort(round(plsa.fit5$prob1[,3], 5), decreasing = T) 


## TOPIC 4 ##
sort(plsa.fit6$prob2[,4], decreasing = T)[1:15] ## ELECTRIC VEHICLE DEVELOPMENT
sort(round(plsa.fit6$prob1[,4], 5), decreasing = T)

sort(plsa.fit5$prob2[,4], decreasing = T)[1:15] ## PUBLIC GRANT
sort(round(plsa.fit5$prob1[,4], 5), decreasing = T) 


## TOPIC 5 ##
sort(plsa.fit6$prob2[,5], decreasing = T)[1:20]   ## US-CHINA ENERGY
sort(round(plsa.fit6$prob1[,5], 5), decreasing = T)  

sort(plsa.fit5$prob2[,5], decreasing = T)[1:20]   ## ELECTRIC VEHICLE TECHNOLOGY
sort(round(plsa.fit5$prob1[,5], 5), decreasing = T)  


## TOPIC 6 ##
sort(plsa.fit6$prob2[,6], decreasing = T)[1:20] # VEHICLE EMISSIONS
sort(round(plsa.fit6$prob1[,6], 5), decreasing = T)


# PLSA does not make sense with tfidf
```

